[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
[deploy]
startCommand = "sh -c 'python manage.py migrate --noinput && python manage.py create_staging_admin && daphne -b 0.0.0.0 -p 8000 backend.asgi:application'"
healthcheckPath = "/"
healthcheckTimeout = 120


