# Generated by Django 5.1.4 on 2024-12-22 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("task", models.CharField(max_length=500)),
                ("is_executed", models.BooleanField(default=False)),
                ("run_count", models.IntegerField(default=0)),
                ("max_runs", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
