# Generated by Django 5.1.4 on 2024-12-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user__class_user_age_user_country_user_currentstage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="currentStage",
            new_name="current_stage",
        ),
    ]
