# Generated by Django 5.1.4 on 2024-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_currentstage_user_current_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="no_student_you_teach",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
