# Generated by Django 5.1.4 on 2024-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_useractivity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("student", "student"),
                    ("teacher", "teacher"),
                    ("tutor", "tutor"),
                    ("school_admin", "school_admin"),
                    ("main_admin", "main_admin"),
                ],
                default="user",
                help_text="User's role in the system",
                max_length=20,
            ),
        ),
    ]
