# Generated by Django 5.1.4 on 2025-01-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_course_instructor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("id", "order")},
        ),
    ]
