# Generated by Django 5.1.4 on 2025-01-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_transactionhistory"),
        ("core", "0013_alter_lesson_unique_together"),
    ]

    operations = []
