# Generated by Django 5.1.4 on 2025-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_merge_20250119_0140"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonquizoption",
            name="option_label",
            field=models.CharField(
                blank=True,
                choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D"), ("e", "E")],
                max_length=2,
                null=True,
                verbose_name="Option label",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonquizoption",
            unique_together={("lesson_quiz", "option_label")},
        ),
    ]
