# Generated by Django 5.1.4 on 2025-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_lessonquizoption_option_label_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonquizoption",
            options={
                "ordering": ["lesson_quiz", "option_label"],
                "verbose_name": "Lesson Quiz Option",
                "verbose_name_plural": "Lesson Quiz Options",
            },
        ),
        migrations.AlterField(
            model_name="lessonquizoption",
            name="text_option",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Text Option"
            ),
        ),
    ]
