# Generated by Django 5.1.4 on 2025-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_courseenrollment_userlessonprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonprogress",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usermoduleprogress",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
