# Generated by Django 5.1.4 on 2025-01-22 10:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_coursestreak"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                        verbose_name="Rating Score",
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="core.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_rating",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Rating",
                "verbose_name_plural": "Course Ratings",
                "unique_together": {("course", "user")},
            },
        ),
        migrations.CreateModel(
            name="LessonRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Rating for lesson (1-5 stars)",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating Score",
                    ),
                ),
                (
                    "rating_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bad", "Bad"),
                            ("very_bad", "Very Bad"),
                            ("good", "Good"),
                            ("very_good", "Very Good"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[("video", "Video"), ("audio", "Audio")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Rating",
                "verbose_name_plural": "Lesson Ratings",
                "unique_together": {("lesson", "user")},
            },
        ),
    ]
