# Generated by Django 5.1.4 on 2025-01-22 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_coursestreak"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qoutes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("quantity_left", models.PositiveIntegerField(default=0)),
                ("class_name", models.CharField(max_length=100)),
                ("term", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "pending"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("is_paused", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("term_start", models.DateTimeField()),
                ("term_end", models.DateTimeField()),
                (
                    "course_pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.coursepathway",
                        verbose_name="Course Pathway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qoute",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.CreateModel(
            name="QouteToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("token", models.CharField(max_length=6, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "qoute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.qoutes",
                        verbose_name="Qoute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qoute Token",
                "verbose_name_plural": "Qoute Tokens",
                "unique_together": {("user", "qoute")},
            },
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="quote_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.qoutetoken",
                verbose_name="Quote Token",
            ),
        ),
    ]
