# Generated by Django 5.1.4 on 2025-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_qoutes_qoutetoken_courseenrollment_quote_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qoutes",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
