# Generated by Django 5.1.4 on 2025-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_qoutes_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qoutetoken",
            name="token",
            field=models.CharField(max_length=6),
        ),
    ]
