# Generated by Django 5.1.4 on 2025-01-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_qoutetoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="qoutes",
            name="level",
            field=models.CharField(
                choices=[
                    ("1", "Level 1 (Beginner: pri 1 - 3)"),
                    ("2", "Level 2 (Beginner: pri 4)"),
                    ("3", "Level 3 (Beginner: pri 5 - 6)"),
                    ("4", "Level 4 (Intermediate: Jss 1 - 2)"),
                    ("5", "Level 5 (Intermediate: Jss 3)"),
                    ("6", "Level 6 (Advanced: SS1)"),
                    ("7", "Level 7 (Advanced: SS2)"),
                ],
                default="1",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("1", "Level 1 (Beginner: pri 1 - 3)"),
                    ("2", "Level 2 (Beginner: pri 4)"),
                    ("3", "Level 3 (Beginner: pri 5 - 6)"),
                    ("4", "Level 4 (Intermediate: Jss 1 - 2)"),
                    ("5", "Level 5 (Intermediate: Jss 3)"),
                    ("6", "Level 6 (Advanced: SS1)"),
                    ("7", "Level 7 (Advanced: SS2)"),
                ],
                max_length=100,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="stage",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advance", "Advanced"),
                ],
                max_length=100,
                verbose_name="Stage",
            ),
        ),
    ]
