# Generated by Django 5.1.4 on 2025-01-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_courserating_lessonrating"),
        ("core", "0024_qoutes_level_alter_course_level_alter_course_stage"),
    ]

    operations = []
