# Generated by Django 5.1.4 on 2025-01-23 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_merge_20250123_1213"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEarnedPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("lesson_completed", "Lesson Completed"),
                            ("module_completed", "Module Completed"),
                            ("course_completed", "Course Completed"),
                            ("assignment_submitted", "Assignment Submitted"),
                            ("quiz_submitted", "Quiz Submitted"),
                            ("daily_activity", "Daily Activity"),
                        ],
                        max_length=20,
                        verbose_name="Point Type",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
