# Generated by Django 5.1.4 on 2025-01-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userearnedpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userearnedpoint",
            name="point_type",
            field=models.CharField(
                choices=[
                    ("lesson_completed", "Lesson Completed"),
                    ("module_completed", "Module Completed"),
                    ("course_completed", "Course Completed"),
                    ("assignment_submitted", "Assignment Submitted"),
                    ("quiz_submitted", "Quiz Submitted"),
                    ("daily_activity", "Daily Activity"),
                    ("streak", "Streak"),
                ],
                max_length=20,
                verbose_name="Point Type",
            ),
        ),
    ]
