# Generated by Django 5.1.4 on 2025-01-23 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_userearnedpoint_point_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonquiz",
            name="allocated_time",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.30"), max_digits=12
            ),
        ),
    ]
