# Generated by Django 5.1.4 on 2025-01-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_lessonquiz_allocated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="badge_icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_badge",
                to="core.media",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="badge_icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_badge",
                to="core.media",
            ),
        ),
    ]
