# Generated by Django 5.1.4 on 2025-01-26 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_course_badge_icon_module_badge_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qoutes",
            name="class_name",
            field=models.CharField(
                choices=[
                    ("primary_1", "Primary 1"),
                    ("primary_2", "Primary 2"),
                    ("primary_3", "Primary 3"),
                    ("primary_4", "Primary 4"),
                    ("primary_5", "Primary 5"),
                    ("primary_6", "Primary 6"),
                    ("jss_1_year_7", "JSS 1/Year 7"),
                    ("jss_2_year_8", "JSS 2/Year 8"),
                    ("jss_3_year_9", "JSS 3/Year 9"),
                    ("sss_1_year_10", "SSS 1/Year 10"),
                    ("sss_2_year_11", "SSS 2/Year 11"),
                    ("sss_3_year_12", "SSS 3/Year 12 (Level 1)"),
                    ("level_a", "Level A"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary_1", "Primary 1"),
                    ("primary_2", "Primary 2"),
                    ("primary_3", "Primary 3"),
                    ("primary_4", "Primary 4"),
                    ("primary_5", "Primary 5"),
                    ("primary_6", "Primary 6"),
                    ("jss_1_year_7", "JSS 1/Year 7"),
                    ("jss_2_year_8", "JSS 2/Year 8"),
                    ("jss_3_year_9", "JSS 3/Year 9"),
                    ("sss_1_year_10", "SSS 1/Year 10"),
                    ("sss_2_year_11", "SSS 2/Year 11"),
                    ("sss_3_year_12", "SSS 3/Year 12 (Level 1)"),
                    ("level_a", "Level A"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AssignedClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("primary_1", "Primary 1"),
                            ("primary_2", "Primary 2"),
                            ("primary_3", "Primary 3"),
                            ("primary_4", "Primary 4"),
                            ("primary_5", "Primary 5"),
                            ("primary_6", "Primary 6"),
                            ("jss_1_year_7", "JSS 1/Year 7"),
                            ("jss_2_year_8", "JSS 2/Year 8"),
                            ("jss_3_year_9", "JSS 3/Year 9"),
                            ("sss_1_year_10", "SSS 1/Year 10"),
                            ("sss_2_year_11", "SSS 2/Year 11"),
                            ("sss_3_year_12", "SSS 3/Year 12 (Level 1)"),
                            ("level_a", "Level A"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
