# Generated by Django 5.1.4 on 2025-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_interest_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
