# Generated by Django 5.1.4 on 2025-01-26 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("competition", "Competition"),
                            ("techpreneurship", "Tech Preneurship"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Content Type",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("link", models.URLField()),
                (
                    "team_members",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
