# Generated by Django 5.1.4 on 2025-01-27 06:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_portfoliocontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherCourseEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_courses",
                        to="core.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.qoutes",
                        verbose_name="Quote",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_teacher",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Course Enrollment",
                "verbose_name_plural": "Teacher Course Enrollments",
                "unique_together": {("quote", "course")},
            },
        ),
        migrations.CreateModel(
            name="TeacherUserLessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Last Video Position"
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "started_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started On"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=True, verbose_name="Is Locked"),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_lessons",
                        to="core.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_lesson",
                        to="core.qoutes",
                        verbose_name="Quote",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_teacher_lesson",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Lesson Progress",
                "verbose_name_plural": "Teacher Lesson Progress",
                "unique_together": {("quote", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="TeacherUserModuleProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "started_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started On"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=True, verbose_name="Is Locked"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_modules",
                        to="core.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_module",
                        to="core.qoutes",
                        verbose_name="Quote",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_teacher_modules",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Module Progress",
                "verbose_name_plural": "Teacher Module Progress",
                "unique_together": {("quote", "module")},
            },
        ),
    ]
