# Generated by Django 5.1.4 on 2025-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_teachercourseenrollment_teacheruserlessonprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
