# Generated by Django 5.1.4 on 2025-02-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_course_term"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
    ]
