# Generated by Django 5.1.4 on 2025-02-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_lesson_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="module",
            unique_together=set(),
        ),
    ]
