# Generated by Django 5.1.4 on 2025-03-02 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="intro_video",
            field=models.TextField(blank=True, null=True, verbose_name="Intro Video"),
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
            },
        ),
    ]
