# Generated by Django 5.1.4 on 2025-04-11 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_library"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetermineCareerInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "age_grp",
                    models.CharField(
                        choices=[
                            ("5-7", "5-7"),
                            ("8-10", "8-10"),
                            ("11-14", "11-14"),
                            ("15-18", "15-18"),
                        ],
                        max_length=10,
                        verbose_name="Age Group",
                    ),
                ),
                ("qus", models.TextField(verbose_name="Question")),
                ("options", models.JSONField(default=dict, verbose_name="Options")),
            ],
            options={
                "verbose_name": "Determine Career Interest",
                "verbose_name_plural": "Determine Career Interests",
            },
        ),
    ]
