# Generated by Django 5.1.4 on 2025-04-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_determinecareerinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="determinecareerinterest",
            name="pathway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_interest_pathway",
                to="core.coursepathway",
                verbose_name="Course Pathway",
            ),
        ),
        migrations.AddField(
            model_name="determinecareerinterest",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("determine_interest", "Determine Interest"),
                    ("determine_interest_level", "Determine Interest Level"),
                ],
                default="determine_interest",
                max_length=50,
                verbose_name="Question Type",
            ),
        ),
    ]
