# Generated by Django 5.1.4 on 2025-04-11 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_discountcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="used_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Used Count"),
        ),
        migrations.CreateModel(
            name="UsedDiscountCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date Updated"
                    ),
                ),
                ("is_fake_data", models.BooleanField(default=False)),
                (
                    "discount_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.discountcode",
                        verbose_name="Discount Code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Used Discount Code",
                "verbose_name_plural": "Used Discount Codes",
                "unique_together": {("user", "discount_code")},
            },
        ),
    ]
