# Generated by Django 5.1.4 on 2025-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_discountcode_used_count_useddiscountcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
