# Generated by Django 5.1.4 on 2025-04-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_discountcode_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="determinecareerinterest",
            name="correct_answer",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Correct Answer"
            ),
        ),
    ]
