# Generated by Django 5.1.4 on 2025-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_determinecareerinterest_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprojectresponse",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Feedback"),
        ),
        migrations.AddField(
            model_name="moduleassignmentresponse",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Feedback"),
        ),
    ]
