# Generated by Django 5.1.4 on 2026-04-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_courseprojectresponse_feedback_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
    ]
